import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />

        <div
          className=" min-h-screen bg-[#e0f7e9] 
            bg-[length:40px_40px] 
            bg-[linear-gradient(to_right,#a8e6cf_1px,transparent_1px),linear-gradient(to_bottom,#a8e6cf_1px,transparent_1px)]"
        >
          {children}
        </div>

        <Footer />
      </body>
    </html>
  );
}
